### ISSUE TITLE
[BUG] Some items aren't displayed in /is shop

### ISSUE THREAD

**Issue by giuliopft** [IridiumLLC/IridiumSkyblock#101]
**Describe the bug**
Some items (at the moment, I only know about cakes, redstone repeaters and redstone comparators, but there might be ) aren't displayed in /is shop when using Spigot 1.8 (I haven't tried out with any newer version yet): instead, the specified slot fills with air.

**To Reproduce**
1. Go into shop.yml
2. Paste this code:
```yml
        {
          "material": "REPEATER",
          "displayName": "",
          "amount": 10,
          "buyVault": 1272.0,
          "sellVault": 471.0,
          "buyCrystals": 0,
          "sellCrystals": 0,
          "slot": 5,
          "page": 1
        }
```
3. Reload the plugin and type /is shop

**Screenshots**
Screenshot available [here](https://i.badlion.net/hp5PXSXQqTGuMH4j52WFeA.png)
